### ISSUE TITLE
Include instructions for setting TZ in Dockerfile

### ISSUE THREAD

**Issue by chasrmartin** [kmontg/xv6-docker#1]
PROBLEM:

Dockerfile needs a TZ setting or it hangs up in the apt-get install at line 6

For example in US/Eastern time should include at line 2,3
```
ENV TZ=US/Eastern
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```
 This should just go in the README

**Comment by kmontg** [comment]
I just made some changes and didn't observe this issue when re-building the image. I'm going to close for now but please re-open if you have steps to reproduce. Thanks!
